### ISSUE TITLE
同人イベントの追加要望

### ISSUE THREAD

**Issue by hosigaki09** [96ENU-kuroinu/misskeyBlueArchive#11]
ゲーム開発部オンリー「ミッションコンプリート！」
2025-02-22 川崎市産業振興会館 4F

https://x.com/pd_gdd/status/1843262910191341712

**Comment by 96ENU-kuroinu** [comment]
@hosigaki09 
[即売会スケジュール](https://github.com/96ENU-kuroinu/misskeyBlueArchive/wiki/fanzineEventSchedules)のページを更新しました。
